name: cmake

on:
  push:
    paths:
      - "**.cpp"
      - "**.ixx"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/cmake.yml"

env:
  CTEST_NO_TESTS_ACTION: error
  CTEST_PARALLEL_LEVEL: 0


jobs:
  linux-clang:
    runs-on: ubuntu-24.04
    env:
      CXX: clang++
    steps:
      - uses: actions/checkout@v5
      - run: cmake --workflow default

  windows-gcc:
    runs-on: windows-2025
    env:
      CXX: g++
    steps:
      - uses: actions/checkout@v5
      - run: cmake --workflow default
  windows-clang:
    runs-on: windows-2025
    env:
      CXX: clang++
    steps:
      - uses: actions/checkout@v5
      - run: cmake --workflow default
